In [1]:
import pandas as pd
import numpy as np

In [3]:
uri = 'https://gist.githubusercontent.com/guilhermesilveira/4d1d4a16ccbf6ea4e0a64a38a24ec884/raw/afd05cb0c796d18f3f5a6537053ded308ba94bf7/car-prices.csv'
df = pd.read_csv(uri)

In [4]:
df.head()

   Unnamed: 0  mileage_per_year  model_year      price sold
0           0             21801        2000   30941.02  yes
1           1              7843        1998   40557.96  yes
2           2              7109        2006   89627.50   no
3           3             26823        2015   95276.14   no
4           4              7935        2014  117384.68  yes

In [5]:
df.drop(columns=["Unnamed: 0"], inplace = True)

In [6]:
df

      mileage_per_year  model_year      price sold
0                21801        2000   30941.02  yes
1                 7843        1998   40557.96  yes
2                 7109        2006   89627.50   no
3                26823        2015   95276.14   no
4                 7935        2014  117384.68  yes
...                ...         ...        ...  ...
9995             15572        2006   97112.86   no
9996             13246        2002  107424.63  yes
9997             13018        2014   93856.99   no
9998             10464        2011   51250.57  yes
9999             12362        1999   87945.73   no

[10000 rows x 4 columns]

In [7]:
df.model_year = df.model_year.apply(lambda x: 2019 - x)

In [9]:
df.mileage_per_year = df.mileage_per_year.apply(lambda x: x * 1.60934)

In [10]:
df

      mileage_per_year  model_year      price sold
0          35085.22134          19   30941.02  yes
1          12622.05362          21   40557.96  yes
2          11440.79806          13   89627.50   no
3          43167.32682           4   95276.14   no
4          12770.11290           5  117384.68  yes
...                ...         ...        ...  ...
9995       25060.64248          13   97112.86   no
9996       21317.31764          17  107424.63  yes
9997       20950.38812           5   93856.99   no
9998       16840.13376           8   51250.57  yes
9999       19894.66108          20   87945.73   no

[10000 rows x 4 columns]

In [11]:
df.sold = df.sold.apply(lambda x: 1 if x == "yes" else 0)

In [12]:
df

      mileage_per_year  model_year      price  sold
0          35085.22134          19   30941.02     1
1          12622.05362          21   40557.96     1
2          11440.79806          13   89627.50     0
3          43167.32682           4   95276.14     0
4          12770.11290           5  117384.68     1
...                ...         ...        ...   ...
9995       25060.64248          13   97112.86     0
9996       21317.31764          17  107424.63     1
9997       20950.38812           5   93856.99     0
9998       16840.13376           8   51250.57     1
9999       19894.66108          20   87945.73     0

[10000 rows x 4 columns]

In [13]:
df.rename(columns= {
    "mileage_per_year": "km",
    "model_year" : "years"
},
inplace = True)

In [15]:
df

               km  years      price  sold
0     35085.22134     19   30941.02     1
1     12622.05362     21   40557.96     1
2     11440.79806     13   89627.50     0
3     43167.32682      4   95276.14     0
4     12770.11290      5  117384.68     1
...           ...    ...        ...   ...
9995  25060.64248     13   97112.86     0
9996  21317.31764     17  107424.63     1
9997  20950.38812      5   93856.99     0
9998  16840.13376      8   51250.57     1
9999  19894.66108     20   87945.73     0

[10000 rows x 4 columns]

In [16]:
from sklearn.model_selection import train_test_split

X = df.drop(columns = ["sold"])
y = df["sold"]

x_train, x_test, y_train, y_test = train_test_split(X, y, random_state = 42)

In [17]:
from sklearn.tree import DecisionTreeClassifier

tree_clf = DecisionTreeClassifier(max_depth = 5)
tree_clf.fit(x_train, y_train)
tree_clf.score(x_test, y_test)

0.7732

In [18]:
from sklearn.tree import export_graphviz
import graphviz

dot_data = export_graphviz(tree_clf, out_file = None)
graph = graphviz.Source(dot_data)
graph

ExecutableNotFound: failed to execute PosixPath('dot'), make sure the Graphviz executables are on your systems' PATH