<a href="https://colab.research.google.com/github/henricobela/manipulando_dados_com_colab/blob/main/Manipulando_um_Dataset_Spotify.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# DATASET UTILIZADO
https://www.kaggle.com/datasets/muhmores/spotify-top-100-songs-of-20152019

## Documentação pandas para manipulação
https://pandas.pydata.org/docs/getting_started/intro_tutorials/03_subset_data.html#min-tut-03-subset

### **iniciando a manipulação**

In [27]:
#importando as bibliotecas a serem utilizadas
import pandas as pd      #importa a biblioteca Pandas e define ela como pd para abreviação

In [28]:
df = pd.read_csv(r"Spotify 2010 - 2019 Top 100.csv")       # guarda na variavel "df" a leitura do arquivo csv especificado utilizando o pandas = pd.read_csv(r"alguma coisa")

In [29]:
df                                                         # mostra na tela a variavel "df" que contem a leitura do arquivo csv especificado - tbm pode ser utilizado print(df)

,title,artist,top genre,year released,added,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop,top year,artist type
0,STARSTRUKK (feat. Katy Perry),3OH!3,dance pop,2009.0,2022‑02‑17,140.0,81.0,61.0,-6.0,23.0,23.0,203.0,0.0,6.0,70.0,2010.0,Duo
1,My First Kiss (feat. Ke$ha),3OH!3,dance pop,2010.0,2022‑02‑17,138.0,89.0,68.0,-4.0,36.0,83.0,192.0,1.0,8.0,68.0,2010.0,Duo
2,I Need A Dollar,Aloe Blacc,pop soul,2010.0,2022‑02‑17,95.0,48.0,84.0,-7.0,9.0,96.0,243.0,20.0,3.0,72.0,2010.0,Solo
3,Airplanes (feat. Hayley Williams of Paramore),B.o.B,atl hip hop,2010.0,2022‑02‑17,93.0,87.0,66.0,-4.0,4.0,38.0,180.0,11.0,12.0,80.0,2010.0,Solo
4,Nothin' on You (feat. Bruno Mars),B.o.B,atl hip hop,2010.0,2022‑02‑17,104.0,85.0,69.0,-6.0,9.0,74.0,268.0,39.0,5.0,79.0,2010.0,Solo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
998,Strike a Pose (feat. Aitch),Young T & Bugsey,afroswing,2019.0,2020‑08‑20,138.0,58.0,53.0,-6.0,10.0,59.0,214.0,1.0,10.0,67.0,2019.0,Duo
999,The London (feat. J. Cole & Travis Scott),Young Thug,atl hip hop,2019.0,2020‑06‑22,98.0,59.0,80.0,-7.0,13.0,18.0,200.0,2.0,15.0,75.0,2019.0,Solo
1000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
df.head(5)                                                 # mostra na tela os 5 primeiros registros da tabela

,title,artist,top genre,year released,added,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop,top year,artist type
0,STARSTRUKK (feat. Katy Perry),3OH!3,dance pop,2009.0,2022‑02‑17,140.0,81.0,61.0,-6.0,23.0,23.0,203.0,0.0,6.0,70.0,2010.0,Duo
1,My First Kiss (feat. Ke$ha),3OH!3,dance pop,2010.0,2022‑02‑17,138.0,89.0,68.0,-4.0,36.0,83.0,192.0,1.0,8.0,68.0,2010.0,Duo
2,I Need A Dollar,Aloe Blacc,pop soul,2010.0,2022‑02‑17,95.0,48.0,84.0,-7.0,9.0,96.0,243.0,20.0,3.0,72.0,2010.0,Solo
3,Airplanes (feat. Hayley Williams of Paramore),B.o.B,atl hip hop,2010.0,2022‑02‑17,93.0,87.0,66.0,-4.0,4.0,38.0,180.0,11.0,12.0,80.0,2010.0,Solo
4,Nothin' on You (feat. Bruno Mars),B.o.B,atl hip hop,2010.0,2022‑02‑17,104.0,85.0,69.0,-6.0,9.0,74.0,268.0,39.0,5.0,79.0,2010.0,Solo

In [31]:
artist = df['artist']                                      # seleciona a coluna 'artist' da tabela, e guarda em uma variavel artist

In [32]:
artist.head(5)                                             # mostra os 5 primeiros registros da coluna 'artist' que foi guardada na variavel artist

0         3OH!3
1         3OH!3
2    Aloe Blacc
3         B.o.B
4         B.o.B
Name: artist, dtype: object

In [33]:
artist.shape                                               # mostra o "corpo" da coluna, no caso quantidade de linhas da coluna

(1003,)

In [34]:
release = df['year released']                              # seleciona a coluna 'year released' da tabela, e guarda em uma variavel release

In [35]:
newRelease = df[df['year released'] > 2011]                # guarda na variavel todos os anos acima de 2011

In [36]:
newRelease.head(5)                                         # mostra na tela a variavel com os 5 primerios registros

,title,artist,top genre,year released,added,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop,top year,artist type
39,California Gurls,Katy Perry,dance pop,2012.0,2022‑02‑17,125.0,75.0,79.0,-4.0,16.0,43.0,235.0,0.0,6.0,78.0,2010.0,Solo
68,This Ain't a Love Song,Scouting For Girls,dance pop,2017.0,2022‑02‑17,177.0,91.0,46.0,-4.0,38.0,55.0,211.0,0.0,5.0,58.0,2010.0,Band/Group
69,Eenie Meenie,Sean Kingston,dance pop,2020.0,2022‑02‑17,121.0,64.0,73.0,-3.0,10.0,84.0,202.0,3.0,3.0,72.0,2010.0,Solo
98,We No Speak Americano (Edit),Yolanda Be Cool,australian dance,2020.0,2022‑02‑17,125.0,81.0,90.0,-5.0,9.0,75.0,157.0,7.0,5.0,65.0,2010.0,Duo
116,Bounce (feat. Kelis) - Radio Edit,Calvin Harris,dance pop,2012.0,2020‑06‑16,128.0,96.0,78.0,-2.0,66.0,76.0,222.0,3.0,4.0,67.0,2011.0,Solo

In [37]:
newRelease.shape                                           # mostra o "corpo" da coluna, no caso quantidade de linhas da coluna

(788, 17)

In [38]:
print("Continua...")

Continua...